[common]
private_key="0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a"
community_list_manager_address="XtqCwjxBKtJtCEFSKFzeLLFYWGuaZ7oYzEyvwz93FsqqJPk"
community_token_address="XtqCwjxBKtJtCEFSKFzeLLFYWGuaZ7oYzEyvwz93FsqqJPk"
blockchain_url="ws://127.0.0.1:9944"

[community]
community_name="Test Community"
community_description="This is test. url:https://test.com"
contribution_check_interval=10

[community_sub_token]
community_sub_token_name="TEST"
community_sub_token_symbol="TST"
