[common]
private_key="0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a"
community_list_manager_address="aD59haoXEZdTrDczk2VM25cMzFghrUckbYkdUYeCmMeDzqp"
community_token_address="ao5NuDYms9EXpzVSE2A5wcyQLQE4CGdgiwEvbE2oCwU75W1"
blockchain_url="ws://127.0.0.1:9944"

[community]
community_name="Test Community 2"
community_description="This is test 2. url:https://test.com"
contribution_check_interval=10

[community_sub_token]
community_sub_token_name="TEST 2"
community_sub_token_symbol="TST 2"
